sudo: false
language: ruby

matrix:
  include:
    # ActiveRecord 4.2
    - rvm: 2.3
      gemfile: gemfiles/rails42.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails42.gemfile

    # ActiveRecord 5.0
    - rvm: 2.3
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails50.gemfile

    # ActiveRecord 5.1
    - rvm: 2.3
      gemfile: gemfiles/rails51.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails51.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails51.gemfile

    # ActiveRecord 5.2
    - rvm: 2.4
      gemfile: gemfiles/rails52.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails52.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails52.gemfile

    # ActiveRecord 6.0.rc1
    - rvm: 2.5.3
      gemfile: gemfiles/rails60.rc1.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails60.rc1.gemfile
